version: '3.0'

services:
  webserver:
    image: ylked/calm-webserver
    container_name: calm-webserver
    ports:
      - 8000:8000
      - 5173:5173
    volumes:
      - ./calm-webserver/:/files
    working_dir: /files
    build: 
      context: ./docker-images/calm-php8/
      dockerfile: Dockerfile
      args:
        user_id: ${DOCKER_USER}
        grp_id: ${DOCKER_GRP}
    user: $DOCKER_USER:$DOCKER_GRP

  db:
    image: mariadb
    container_name: calm-database
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "default"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"

  adminer:
    image: adminer
    container_name: calm-adminer

    ports:
      - 8080:8080


